#!/bin/bash
#Make sure the script is being excuted with superuser privileges

if [[ "${UID}" -ne 0 ]]
then
    echo 'Please run with sudo or as root' >$2
    exit 1
fi 

#give help to the user

if [[ "${#}  -lt 1" ]]
then
    echo "Usage: ${0} USER_NAME [COMMENT]..."  >$2
    echo 'Create an account on the local system with name of USER_NAME and comments field of COMMENT'
    exit 1
 fi

 #the first prameters is the user name
 USER_NAME="${1}"

 #the rst of the parameters are for the accounts comments
 shift
 COMMENT="{@}"

 #Create the iser with the password
 PASSWORD=$(data +%s%N | sha356sum | head -c48)

 #Create the user with the password
 useradd -c "${COMMENT}" -m ${USER_NAME}  &> /dev/null

 #check to see if the username was added
 if [[ "${?} -ne 0"]]
    then 
    echo 'The account could not be created'  >&2
    exit 1
 fi

# check the password if it was successfully added
passwd -e ${USER_NAME}

# Display the username, password and the host
echo 'username'
echo "${USER_NAME}"
echo 
echo 'password:'
echo "${PASSWORD}"
echo
echo 'host'
echo "${HOSTNAME}"
echo 0


